name: GG-LAN CI/CD PROD

on:
  push:
    branches: ["master"]

jobs:
  deploy-to-prod:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port:     ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/gg-lan-admin
            git checkout master
            git pull

            composer install --no-dev --no-progress --no-interaction
            npm install

            php artisan migrate
            php artisan filament:optimize-clear
            php artisan filament:optimize
            php artisan optimize:clear
            php artisan optimize
            php artisan queue:restart

            npm run build